services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: development
    ports:
      - "4000:5000"
    develop: 
      watch:
        - action: sync
          path: .
          target: /code
    volumes:
      - ./app.py:/app/app.py
    command: python app.py
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_DEBUG=True
      - DB_HOST=db
      - DB_NAME=example
      - DB_USER=root
  
  db:
    image: mariadb
    restart: always
    user: root
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment: 
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_DATABASE=spost
    expose: 
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_HOST=db

volumes:
  db-data:
  
secrets:
  db-password:
    file: db/password.txt
