x-app: &default-app
  build:
    context: .
    dockerfile: ./docker/Dockerfile
    target: app-final
  secrets:
    - db-password
  restart: unless-stopped
  depends_on:
    db:
      condition: service_healthy
      required: false
  env_file:
    - ".env"


services:
  db:
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD_FILE: "${MARIADB_ROOT_PASSWORD_FILE}" 
      MARIADB_DATABASE: "${MARIADB_NAME}"
    expose: 
      - "${MARIADB_PORT:-3306}"
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  web:
    <<: *default-app
    ports:
      - "8000:${PORT:-8000}"

volumes:
  db-data:
  
secrets:
  db-password:
    file: db/password.txt
