services:
  web:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      target: app-final
    ports:
      - "8000:${PORT:-8000}"
    secrets:
      - db-password
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ".env"
  
  db:
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD_FILE: "${MARIADB_ROOT_PASSWORD_FILE}" 
      MARIADB_DATABASE: "${MARIADB_NAME}"
    expose: 
      - 3306
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  
secrets:
  db-password:
    file: db/password.txt
